# Generated by Django 6.1 on 2026-08-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Grants access to admin-only actions(e.g. stock adjustments, user approvals, role management).regradless of the module permissions flags.'),
        ),
    ]
