# Generated by Django 6.1 on 2026-08-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='is_admin',
            new_name='is_admin_role',
        ),
    ]
