# Generated by Django 6.1 on 2026-08-25 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('EXPIRING_DRUG', 'Expiring Drug'), ('MISSED_MEDICATION', 'Missed Medication'), ('UPCOMING_REVIEW', 'Upcoming Review'), ('OUTSTANDING_BILL', 'Outstanding Bill')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('dedupe_key', models.CharField(blank=True, max_length=150)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_read', False)), fields=('recipient', 'dedupe_key'), name='unique_unread_notification_per_recipient_key')],
            },
        ),
    ]
