# Generated by Django 6.1 on 2026-09-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('EXPIRING_DRUG', 'Expiring Drug'), ('MISSED_MEDICATION', 'Missed Medication'), ('UPCOMING_REVIEW', 'Upcoming Review'), ('OUTSTANDING_BILL', 'Outstanding Bill'), ('PENDING_LEAVE', 'Pending Leave Request')], max_length=30),
        ),
    ]
