# Generated by Django 6.1 on 2026-09-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_dailybedcharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybedcharge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
