# Generated by Django 6.0.7 on 2026-07-20 18:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_progressnote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('generic_name', models.CharField(blank=True, max_length=150)),
                ('strength', models.CharField(blank=True, max_length=50)),
                ('form', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Injection', 'Injection'), ('Syrup', 'Syrup')], default='Tablet', max_length=20)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('min_stock', models.PositiveIntegerField(default=10)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DispenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_records', to='pharmacy.drug')),
            ],
            options={
                'ordering': ['-dispensed_at'],
            },
        ),
    ]
