# Generated by Django 6.1 on 2026-08-19 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_drug_batch_number_drug_max_stock_drug_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenserecord',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
