# Generated by Django 6.1 on 2026-08-25 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Charged to the patient's bill when used via ConsumableUsage.", max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
