# Generated by Django 6.0.7 on 2026-08-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitysettings',
            name='total_beds',
            field=models.PositiveIntegerField(
                default=50,
                help_text='Total bed capacity across all wards. Used to compute Available Beds on the dashboard.',
            ),
        ),
    ]
