# Generated by Django 6.1 on 2026-08-23 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_trail', '0002_alter_auditlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('VIEW', 'Viewed'), ('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Logged in'), ('FAILED_LOGIN', 'Failed login'), ('LOGOUT', 'Logged out'), ('FORCE_LOGOUT', 'Forced logout'), ('REGISTER', 'Registered account'), ('APPROVE_USER', 'Approved user'), ('ROLE_CHANGE', 'Changed user role'), ('PERMISSION_CHANGE', 'Changed role permissions'), ('PASSWORD_CHANGE', 'Changed password'), ('MFA_ENABLED', 'Enabled MFA'), ('MFA_DISABLED', 'Disabled MFA'), ('PAYMENT', 'Recorded payment'), ('REFUND', 'Issued refund'), ('STOCK_ADJUST', 'Adjusted stock'), ('DISPENSE', 'Dispensed medication'), ('LAB_APPROVE', 'Approved lab result'), ('EXPORT', 'Exported data'), ('CONFIG_CHANGE', 'Changed system configuration')], max_length=32),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='audit_trail_action_ba999d_idx'),
        ),
    ]
