# Generated by Django 6.0.7 on 2026-07-19 18:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Name can only contain letters, spaces, hyphens, apostrophes and periods.', regex="^[A-Za-zÀ-ÿ\\s\\.'-]+$")])),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('ward', models.CharField(choices=[('Ward A', 'Ward A'), ('Ward B', 'Ward B'), ('Ward C', 'Ward C')], max_length=20)),
                ('diagnosis', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Admitted', 'Admitted'), ('Discharged', 'Discharged')], default='Admitted', max_length=20)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, help_text='30-250 cm', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(250)])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, help_text='2-300 kg', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(300)])),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, help_text='30.0-43.0 °C (covers severe hypothermia to severe hyperthermia)', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(43.0)])),
                ('pulse_bpm', models.PositiveSmallIntegerField(blank=True, help_text='30-220 bpm', null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(220)])),
                ('blood_pressure', models.CharField(blank=True, help_text='Format: systolic/diastolic, e.g. 120/80', max_length=10, validators=[django.core.validators.RegexValidator(message='Blood pressure must be formatted as systolic/diastolic, e.g. 120/80.', regex='^\\d{2,3}/\\d{2,3}$')])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admitted_patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
