# Generated by Django 6.0.7 on 2026-08-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_progressnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='discharged_at',
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text='Set automatically when status changes to Discharged; cleared if re-admitted.',
                null=True,
            ),
        ),
    ]
