# Generated by Django 6.1 on 2026-08-11 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_drug_buying_price_drug_selling_price_stockaddition'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='drug',
            name='max_stock',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='drug',
            name='supplier',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='stockaddition',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stockaddition',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockaddition',
            name='notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stockaddition',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockaddition',
            name='supplier',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
